[package]
name = "sentiment-analysis-cli"
version = "0.1.0"
edition = "2021"
authors = ["Laurence Sonnenberg <laurence@robothouse.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

clap = { version = "4.4.4", features = ["derive"] }
tokio = { version = "1.32", features = ["macros", "rt-multi-thread", "rt"] }
thiserror = "1.0.48"
colored = "2.0.4"
[dependencies]
clap = { version = "4.4.13", features = ["derive"] }